---

apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    creator: chaitu
    type: database
spec:
  containers:
    - name: mydb
      image: mysql
      env:
        - name: MYSQL_PASSWORD
          value: chaitu


...
